### PR TITLE
Add Georgian phonology and converter

### PR DESCRIPTION
**Pull request by parryc**
@alkaitagi, added phonology, converter, and sample phrasebook sentence for Georgian. When you have a moment, would you mind telling me what is wrong with the `converter.json` file? Only the first two pairs work (format copied off of Iron). 

I admit, I am a bit confused by the converter page and how to design the pairing. For example, it seems a bit counter-intuitive that the 2nd mapping should be blank.

### CODE REVIEW

**Comment by alkaitagi** [comment]
Thank you very much for your contribution. I've just pushed the much-awaited technical update, so it's right on time. The rewrite is not completely ready in the sense that there still will be some warnings upon compiling the source, but it is fully functional and the new architecture is set. I hope to clean up those by the end of the week.

The most notable change is that now all JSON is being stored and subsequently served from the *storage* branch on the repo. I believe this separation of linguistic data from the main app source allows for a cleaner local workflow and easier content pull requesting. Also, all content modifications (by committing or pull requesting into the *storage* branch) will now appear on the site under 5 minutes as per GitHub's caching timeout, without the need for the app recompilation.

image

When in production mode, the app fetches files directly from the branch, and when in development mode, it fetches them from the local path, same a before. To enable local testing, copy the *storage* branch into your local copy of the *main* branch, under the **static** folder. It will not leak into the main branch due to the **.gitignore** update, as the *main* branch now contains only app source.

image

There are 4 minor UI improvements:
1. Reworked map, so it now zooms smoothly and uses vector tiles, which results in sharped image and improved performance.

image

2. Unified and simplified navigation and global controls across all the editor headers.

image

3. Converter Editor now has a small text field where you can test your mappings right away.

image

4. Removed unnecessary Phrasebook display controls, so notes and interactivity are always enabled, as well as cleaned up context display.

image

There are 2 breaking changes in terms of JSON format:
1. In **catalogue.json** property `coordinates` was renamed into `point` and the numbers are swapped.
2. In **converter.json** property `default` was deleted. Now the default conversion pair is always the 0th and the 1st mappings.

**Comment by alkaitagi** [comment]
Now, in terms of Converter, I am perfectly aware that the architecture is confusing and the capabilities are very limited, so it really needs an update, which I hope to work on somewhere at the end of next month, after a minor phrasebook update. The second mapping should be blank because the first mapping already should contain conversion from the sample's script into the immediate script that is used for canonical internal representation, from which all other mappings should be converting.

So really the only incorrect thing about your converter was that the first mapping was converting *from* Georgian, while all mappings should convert *to* Georgian. Also, in the current format, I've kind of implicitly and arbitrarily decided that the sample text should be of a non-canonical script, so the default conversion demonstrates the canonical output. Obviously, this should be reworked, but for now, for the sake of consistency, I've reordered the mappings and set the sample in Nuskhuri.

This is what I've got, and it seems to work (Though I can't confirm not knowing the language):

image

**Comment by alkaitagi** [comment]
I am closing this pull request while manually committing your changes. For any additions, please refer to the [store branch](https://github.com/alkaitagi/Avzag/tree/store).

image

P.S. It is now perfectly possible to create pull requests directly in GitHub's web UI while authoring the JSON files in the public editors. So, it might not be necessary to keep a local source copy from the *main* branch just for content contributions. But surely it is more convenient to be able to test stuff locally.

**Comment by parryc** [comment]
Thanks for accepting the contribution @alkaitagi, that mapping looks good. It might make more sense to set the default to be "Transcription (National)" as that is more common than Nuskhuri (which is the alphabet used in the middle ages).

**Pull request closed without merging**
